version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
      timezone: "Asia/Seoul"
    target-branch: develop
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/packages/*"
    schedule:
      interval: daily
      time: "21:00"
      timezone: "Asia/Seoul"
    target-branch: develop
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/commons/*"
    schedule:
      interval: daily
      time: "21:00"
      timezone: "Asia/Seoul"
    target-branch: develop
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: "/example/*"
    schedule:
      interval: daily
      time: "21:00"
      timezone: "Asia/Seoul"
    target-branch: develop
    labels:
      - dependencies
